services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  api:
    # build: .
    image: ops-api:latest
    env_file:
      - .env.production
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  redis:
    image: redis:6-alpine
    command: ["redis-server", "--port", "11000"]
    ports:
      - "11000:11000"
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  redis-data:
